# permissions for end users to edit jcascprofiles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jcascprofile-editor-role
rules:
- apiGroups:
  - jenkins.io
  resources:
  - jcascprofiles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - jenkins.io
  resources:
  - jcascprofiles/status
  verbs:
  - get
